# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapInstagramKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapInstagramKit

end

target 'TapInstagramKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapInstagramKitExample
pod "Kingfisher"
end
